# Generated by Django 5.2 on 2025-04-17 12:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resume',
            options={'ordering': ['-created_at'], 'verbose_name': 'резюме', 'verbose_name_plural': 'резюме'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['category', 'name'], 'verbose_name': 'навык', 'verbose_name_plural': 'навыки'},
        ),
        migrations.AddField(
            model_name='skill',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='skill',
            name='slug',
            field=models.SlugField(blank=True, max_length=110, unique=True, verbose_name='URL-идентификатор'),
        ),
        migrations.AddField(
            model_name='skill',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='дата изменения'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.FileField(upload_to='resumes/', verbose_name='файл'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Microsoft Word')], max_length=10, verbose_name='тип файла'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='mongodb_id',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='ID в MongoDB'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='resumes', to='resumes.skill', verbose_name='навыки'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='status',
            field=models.CharField(choices=[('pending', 'В ожидании'), ('analyzing', 'Анализируется'), ('completed', 'Анализ завершен'), ('failed', 'Ошибка анализа')], default='pending', max_length=20, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='title',
            field=models.CharField(max_length=255, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='дата изменения'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('programming', 'Языки программирования'), ('framework', 'Фреймворки и библиотеки'), ('database', 'Базы данных'), ('devops', 'DevOps и инфраструктура'), ('soft_skill', 'Гибкие навыки'), ('language', 'Языки'), ('other', 'Другое')], default='other', max_length=50, verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='название'),
        ),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['user'], name='resumes_res_user_id_4806ca_idx'),
        ),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['status'], name='resumes_res_status_dd2fd3_idx'),
        ),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['created_at'], name='resumes_res_created_4917a2_idx'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['name'], name='resumes_ski_name_b760ea_idx'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['category'], name='resumes_ski_categor_19f278_idx'),
        ),
    ]
